# Automatically build and deploy to GitHub releases by Travis CI

language: node_js
node_js:
  - "node"

cache:
  directories:
    - "node_modules"

branches:
  only:
    - master

before_script:
  - git config --local user.name "SimpleCollector"
  - git config --local user.email "35264312+SimpleCollector@users.noreply.github.com"
  - if [ "$TRAVIS_BRANCH" == "master" ]; then git tag -f "latest-build"; git push -q --force https://$TAG_TOKEN@github.com/SimpleCollector/simplecollector-gui tag latest-build; fi
  - npm install -g @angular/cli@latest
  - npm install

script:
  - ng build --prod
  - cd dist
  - tar cvzf ../simplecollector-gui-dist.tgz *
  - cd ..
      
deploy:
  provider: releases
  api_key:
    secure: "$GITHUB_API_KEY"
  file: "simplecollector-gui-dist.tgz"
  skip_cleanup: true
  overwrite: true
  on:
    repo: SimpleCollector/simplecollector-gui
    tags: true
  
after_deploy:
  # Trigger docker hub build
  - |-
    curl -s -H "Content-Type: application/json" --data '{"source_type": "Branch", "source_name": "master"}' -X POST https://registry.hub.docker.com/u/simplecollector/simplecollector-app/trigger/$DOCKERHUB_TOKEN/

notifications:
  email:
    on_failure: always
    on_success: change
