image: node:6

pipelines:
  default:
    - step:
        caches:
          - node
        script:
          - npm install -g @angular/cli@latest
          - npm install
          - ng build --prod
          - cd dist
          - tar cvzf ../simplecollector-gui-dist.tgz *
          - cd ..
          - curl -X POST --user "${BB_AUTH_STRING}" "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"simplecollector-gui-dist.tgz"
